### ISSUE TITLE
UIFDropDown issues with ng-transclude

### ISSUE THREAD

**Issue by johnnliu** [ngOfficeUIFabric/ng-officeuifabric#370] opened 2016-06-21 04:03 UTC
I wanted to drop a quick note that for IE11 and Edge, we had issues with the dropdown not working (the LI items were not being transcluded inside the UL).

We fixed this by moving the ng-transclude element inside the parent ul.ms-Dropdown-items as an attribute.
### Problem line: dropdown template

`<ul class="ms-Dropdown-items"><ng-transclude></ng-transclude></ul>`
### Fixed

`<ul class="ms-Dropdown-items" ng-transclude></ul>`
### Additional observations

The dropdown demo page works fine in IE11/Edge.  One point of difference is that our view was loaded via angular-route.

I want to test this more thoroughly but also wanted to let other people know how we fixed this one issue.

**Comment by ghost** [comment] 2016-06-23 09:40
We have had other issues with ng-transclude where it did not work properly as an attribute...
Do you recall @andrewconnell  ? Or am I wrong, and did we have issues with ng-transclude as an element?

In any case, happy to change it to attribute if that fixes the issue (needs to be confirmed) and if all test scripts still pass. Would you be able to investigate further @johnnliu ?

**Comment by andrewconnell** [comment] 2016-06-23 09:54
I don't recall that issue... sorry :-/

**Comment by andrewconnell** [comment] 2016-07-25 20:48
@johnnliu Can you replicate the issue with a plunk & post here? If so, we can flag this as a bug... 

Have you seen any other impact from making this change?  If not, do you want to submit a PR fixing it?

**Comment by andrewconnell** [comment] 2016-12-15 11:55
Hey @johnnliu - it's been a while since this was filed... any chance you recall the details around it and what we can do to duplicate / repo the issue? Pushing hard on bug squashing & would love to close this one out...

**Comment by andrewconnell** [comment] 2016-12-21 16:18
Closing due to no response... feel free to re-open @johnnliu with a link to repo so we can take action on it.

**Closed as completed by andrewconnell** 2016-12-21 16:18 UTC
Labels: needs-review, waiting-on-response
