### ISSUE TITLE
Spinner label is wrapped if multiple words are used

### ISSUE THREAD

**Issue by waldekmastykarz** [ngOfficeUIFabric/ng-officeuifabric#151] opened 2016-02-01 15:43 UTC
If the spinner's label consists of multiple words the words are wrapped. You cannot see it in the sample because the label is set to `Loading...`, but if you would change it to `Searching for files...` you would see it wrap.
Ideally the label should be set to spinner's dimensions but it seems like it's a bug in Office UI Fabric. The question is whether we want to fix it ourselves or if we want to submit it as a bug in the Office UI Fabric.

**Comment by andrewconnell** [comment] 2016-02-01 15:47
I think it should be flagged to the Office UI Fabric guys and see what they decide. If they deem it works as designed and it's not a bug, then we can decide what to do. But if they agree it's a bug, I'd rather let them fix it...

If you elect to bug it with them, please reference this issue for tracking...

**Comment by waldekmastykarz** [comment] 2016-02-01 15:53
:+1:

**Comment by waldekmastykarz** [comment] 2016-02-01 16:06
Submitted issue to Office UI Fabric at https://github.com/OfficeDev/Office-UI-Fabric/issues/302

**Comment by andrewconnell** [comment] 2016-02-01 16:42
Seems they've logged it as a bug... we can leave this open and just watch it as it appears to being addressed by fabric. For now... flagging as something we won't fix... but leaving this open for tracking.

**Comment by jjczopek** [comment] 2016-02-01 17:03
Nice catch @waldekmastykarz ;) I'll monitor progress on that as well.

**Comment by waldekmastykarz** [comment] 2016-02-01 17:59
:+1:

For the time being if you're interested in a workaround:

Wrap spinner in an additional div:

``` html
<div class="uif-Spinner-wrapper">
  <uif-spinner ng-show="vm.loading === true">Looking for documents...</uif-spinner>
</div>
```

Add CSS:

``` css
.uif-Spinner-wrapper {
    width: 13em;
    margin: 1em auto; /* center wrapper in its container */
}

.ms-Spinner-label {
    width: 11em;
}
```

`ms-Spinner-label` width depends on the length of your message. `uif-Spinner-wrapper` width is the width of `ms-Spinner-label` + some additional space for the spinner itself.

**Comment by andrewconnell** [comment] 2016-02-05 21:11
Looks like this has been fixed in Fabric v2 in PR https://github.com/OfficeDev/Office-UI-Fabric/pull/308 and issue https://github.com/OfficeDev/Office-UI-Fabric/issues/302

As such I'm going to close this.

**Closed as completed** 2016-02-05 21:11 UTC
Labels: wontfix, verified
