### ISSUE TITLE
Callout: unable to close by button inside

### ISSUE THREAD

**Issue by Rus7am** [ngOfficeUIFabric/ng-officeuifabric#450] opened 2016-12-20 14:22 UTC
I'd like to be able to close a callout with **uif-close** attribute by clicking a button located inside **uif-callout-actions** component. Please see the [codepen](http://codepen.io/Rus7am/pen/rWReJY): after the **Close** button is clicked the `ctrl.show` property is being reset and the callout stays open.

I was hoping to fix this myself but everything is in TypeScript and I don't really understand it yet, sorry.

**Comment by andrewconnell** [comment] 2016-12-21 15:58
~~ATM the `uif-dialog` directive's functionality is very limited. This was one of the very first directives & ideally it would match the same signature and behavior the Office React version would have: https://dev.office.com/fabric#/components/dialog.~~

~~The right thing to do is to not fix this issue, rather to improve the directive to have feature parity with it's React sibling. Going to close this issue out and reference the new feature request issue 455~~

~~FWIW, we already had a discussion going on this issue: # 363~~

**Comment by andrewconnell** [comment] 2016-12-22 14:39
Nixing my previous comment... I got my wires crossed got `uif-dialog` & `uif-callout` backward. This appears to be a similar issue to #358 in the sense that the binding isn't being respected. 

Reopening this and flagging as a bug to be investigated. I believe it's the binding defined here that's the root cause: https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/master/src/components/callout/calloutDirective.ts#L223-L226

Need to add a test to duplicate the bug & then resolve.

**Closed as completed** 2017-01-05 10:55 UTC
Labels: bug, verified
