### ISSUE TITLE
Component to create: button

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#14] opened 2015-12-29 14:04 UTC
Official link to component description & demo: http://dev.office.com/fabric/components/button

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by andrewconnell** [comment] 2015-12-29 15:48
Spec:

``` javascript
<!-- button -->
<!-- http://codepen.io/andrewconnell/pen/gaMzmY -->
<uif-button>Create account</uif-button>

<!-- primary button -->
<!-- http://codepen.io/andrewconnell/pen/epzryV -->
<uif-button uif-type="primary"></uif-button>

<!-- command button -->
<!-- http://codepen.io/andrewconnell/pen/MaedKX -->
<uif-button uif-type="command">
  <uif-icon uif-type="plus" />
  Create account
</uif-button>

<!-- compound button -->
<!-- http://codepen.io/andrewconnell/pen/XmKwjO -->
<uif-button uif-type="compound" 
            disabled="true">
  <uif-button-description>Description for button label</uif-description>
  Create account
</uif-button>

<!-- hero button -->
<!-- http://codepen.io/andrewconnell/pen/ojLdJr -->
<uif-button uif-type="hero">
  <uif-icon uif-type="plus" />
  Create account
</uif-button>
```

~~This would require the creation of two dependent element directives... **uif-icon** & **uif-description**. Need to research if it makes sense to create attribute directives too (**uif-type**)?~~ _resolved in comments below_

The Office UI Fabric supports creating buttons using `<a>`, `<div>` & `<button>` where the last one, `<button>` is recommended. This directive will render them as `<button>` but if the attribute `href` is supplied on a button, it will render it out as an `<a>` so consumers can use a button as a hyperlink. However at this time the button won't support rendering as a `<div>`.

Ref:
- Ignore **data-** prefix for W3C validators... they don't work with web components anyway... Angular Material made the same call, which is good enough for us: https://github.com/angular/material/issues/3458

**Comment by jjczopek** [comment] 2015-12-29 21:44
After short research I'm not sure how about **uif-description**, but I think it should be OK to create **uif-icon** - it looks like other components are using that as well, e.g. ListGrid example (https://github.com/OfficeDev/Office-UI-Fabric/blob/master/src/components/List/List.Grid.html), with icons assigned to ListItem (therefore I also assume it would work for ListItem).

**Comment by andrewconnell** [comment] 2015-12-29 23:01
I struggle with the description as well... But how else to address it? Looks like a span with a class nested within it is how material does it at times

**Comment by jjczopek** [comment] 2015-12-29 23:26
It's a bit tricky after all. My previous example is not the best one, as button wraps `<i>` element in a `<span>`, but for List.Grid, it wraps it in a `<div>`. 
In best case scenario **uif-icon** should output only the **`<i>`** element with appropriate class, but then it would take a lot of effort (or I'm wrong?) to adjust icon handling for different components (assuming putting that logic in the icon directive). Or maybe it would be possible to handle that per component rather than put a lot of conditional logic in icon directive?

**Comment by andrewconnell** [comment] 2015-12-29 23:30
I don't see the icon directive being different across different directives... they all seem to render the same thing out... just the `<i>`.

For other components, I'd have to look at how the material guys handled it...

**Comment by jjczopek** [comment] 2015-12-29 23:44
I agree - icon directive in outputs `<i>` in the end, but from what I saw different components can put some additional wrapping around icons, e. g. for button:

``` html
<button class="ms-Button ms-Button--primary">
    <span class="ms-Button-icon"><i class="ms-Icon ms-Icon--plus"></i></span>
</button>
```

 and for list item:

``` html
<div class="ms-ListItem ms-ListItem--image">
  ...
  <div class="ms-ListItem-actions">
    <div class="ms-ListItem-action"><i class="ms-Icon ms-Icon--mail"></i></div>
    ...
  </div>
</div>
```

I'm just thinking aloud how to handle those different 'wrapping' scenarios - I might be over-thinking the whole thing however.

**Comment by andrewconnell** [comment] 2015-12-29 23:52
No i don't think you are... good observation here. I'll do some investigation in ngmaterial... need to find some instances where they have to deal with it... like if you can have some context to your container

**Comment by waldekmastykarz** [comment] 2015-12-30 08:52
Looking at the examples above, the ListItem icon is wrapped in a div.ms-ListItem-action which seems like a part of ListItem action rather than an icon wrapper. As for the button: why shouldn't the button be responsible for correctly rendering its icon? In that way you would add a button with an icon inside and the button figures out how that icon should be properly wrapped to be rendered as designed in the Fabric. In both cases the icon would remain as-is and the wrapping would be done by the parent component.

**Comment by andrewconnell** [comment] 2015-12-30 10:59
While I see your point, one of the ideas of the directives is to make implementation a bit easier. In the case of list item, agreed... it's part of the action so that's not something you'd add to the icon. But in the case of the button, it's icon+button specific so I would think it would make sense to have either the button / icon know about the wrapper that needs to be rendered.

**Comment by waldekmastykarz** [comment] 2015-12-30 11:27
To what extent is this scenario different than for example handling a textfield with placeholder which also requires additional markup? What if we added an attribute you can set on the button directive which would render the icon markup? I'm not sure if this would allow us to reuse the existing icon directive but it would abstract away the icon markup and make it easier for devs to use buttons with icons.

**Comment by andrewconnell** [comment] 2015-12-30 11:41
Are you proposing...

``` javascript
<uif-button uif-icon="plus">Create Account</uif-buton>
```

I think that's what you're saying. We wouldn't do this... if it's content within the button, which the icon is, then that would be done as you see above in my spec. Doing it this way ^^^ is not great for reuse.

**Comment by waldekmastykarz** [comment] 2015-12-30 11:50
That's what I was thinking about indeed. I've had a quick look at ngMaterial and it seems like they don't have the challenge because Material doesn't use icon wrappers.
Given that icons are reused in different components in Fabric, each having their own wrappers, it would be better if the icon wrapping logic was a part of the component rather than the icon. The latter would require a long switch statement to cater for the different wrappers for different components.

**Comment by andrewconnell** [comment] 2015-12-30 11:57
I'll look at a few different options... we've collectively gone way off topic talking about icons here... there's an issue for icons :) #40 

I've got the simple icon directive working locally... worst case any wrapping can be manually added but I'll look at what wrapping options there are... ideally at the container level (ie: button) and not at the child level (ie: icon).

**Comment by waldekmastykarz** [comment] 2015-12-30 11:59
I've been looking into the possibility of accessing child elements of a directive template. If it worked we could use it to examine the contents of <uif-button> and wrap any <uif-icon> found with additional markup.

**Comment by andrewconnell** [comment] 2016-01-08 11:56
Made a few tweaks to the spec:
- removed **uif-** prefix from the `disabled` attribute... there's already a valid HTML element for disabling controls so why not reuse it as it's less to learn for consumers as it will do the same thing
- added support for telling the directive to render the button using `<button>` or `<a>`

**Comment by jjczopek** [comment] 2016-02-01 22:59
Touching base... how's it going with the directive?

**Comment by andrewconnell** [comment] 2016-02-02 01:59
Totally fair question @jjczopek ! This is a “spare time” project right now… i’m spending most of my time with it managing it (keeping issues updated, merges, etc). Trying to get some stuff done to simplify and distribute this role among us… but until then…

you can see my status on the button in my fork… I’ve got the tests & demo done, just implementing  the directive now: https://github.com/andrewconnell/ng-officeuifabric/tree/issue14-button

**Closed as completed** 2016-02-07 20:36 UTC
Labels: review-complete
